### ISSUE TITLE
Can't Create new account

### ISSUE THREAD

**Issue by Kishinskiy** [scmn-dev/secman#133]
MacOS 12.1

Can't create new account

❯ secman init
✖ 💿 ~/.secman already exists
❯ rm -rf .secman
❯ secman init
✔ 💿 Initialization complete
run `secman auth` to authenticate
❯ secman auth
✔ Enter your email:  … threew82@gmail.com
✔ Enter your master password:  … ***********

Invalid email or master password. if you don't have an account, please create one using the command `secman auth --create-account`.
❯ secman auth --create-account
 ›   Error: Unexpected argument: --create-account
 ›   See more help with --help

**Comment by abdfnx** [comment]
hi @Kishinskiy, run `secman auth --createAccount`

**Comment by abdfnx** [comment]
@Kishinskiy Has the problem been fixed?

**Comment by Kishinskiy** [comment]
Yes. Thanks
