### ISSUE TITLE
Cannot install in macOS using brew

### ISSUE THREAD

**Issue by arcesino** [scmn-dev/secman#175]
**Describe the bug**
secman cannot be installed with HomeBrew using the command in https://secman.dev/download
```
brew tap scmn-dev/secman && brew install secman
````

**To Reproduce**
Simply to install in macOS using command in official docs:
```
brew tap scmn-dev/secman && brew install secman
```

**Expected behavior**
The command in your official installation instructions for HomeBrew should install secman in macOS. It seems to me that you ned to implement correctly `secman.rb` formula in [scmn-dev/homebrew-tap](https://github.com/scmn-dev/homebrew-tap) repo and update the installation instructions to simply use:
```
brew install scmn-dev/tap/secman
```

**Desktop (please complete the following information):**

- OS: macOS Big Sur v11.6
- HomeBrew: v3.4.1

**Additional context**
Following [official installation instructions](https://secman.dev/download) for HomeBrew, this is the command to install it:
```
brew tap scmn-dev/secman && brew install secman
```
but the first command `brew tap scmn-dev/secman` fails with error:
```
❯ brew tap scmn-dev/secman && brew install secman
Running `brew update --preinstall`...
==> Tapping scmn-dev/secman
Cloning into '/usr/local/Homebrew/Library/Taps/scmn-dev/homebrew-secman'...
remote: Enumerating objects: 193, done.
remote: Counting objects: 100% (193/193), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 193 (delta 44), reused 164 (delta 36), pack-reused 0
Receiving objects: 100% (193/193), 23.33 KiB | 1.06 MiB/s, done.
Resolving deltas: 100% (44/44), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/scmn-dev/homebrew-secman/secman.rb
No available formula with the name "secman".
In formula file: /usr/local/Homebrew/Library/Taps/scmn-dev/homebrew-secman/secman.rb
Expected to find class Secman, but found no classes.
Error: Cannot tap scmn-dev/secman: invalid syntax in tap!
```
since it's looking for a repo **scmn-dev/homebrew-secman** that's not [in your repos](https://github.com/orgs/scmn-dev/repositories?q=homebrew&type=all&language=&sort=). There is this other repo [scmn-dev/homebrew-tap](https://github.com/scmn-dev/homebrew-tap) with a [secman.rb](https://github.com/scmn-dev/homebrew-tap/blob/master/secman.rb) formula that could be installed with:
```
brew install scmn-dev/tap/secman
```
as this repo's README states, but it also fails with error:
```
❯ brew install scmn-dev/tap/secman
==> Tapping scmn-dev/tap
Cloning into '/usr/local/Homebrew/Library/Taps/scmn-dev/homebrew-tap'...
remote: Enumerating objects: 193, done.
remote: Counting objects: 100% (193/193), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 193 (delta 44), reused 164 (delta 36), pack-reused 0
Receiving objects: 100% (193/193), 23.33 KiB | 426.00 KiB/s, done.
Resolving deltas: 100% (44/44), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/scmn-dev/homebrew-tap/secman.rb
No available formula with the name "secman".
In formula file: /usr/local/Homebrew/Library/Taps/scmn-dev/homebrew-tap/secman.rb
Expected to find class Secman, but found no classes.
Error: Cannot tap scmn-dev/tap: invalid syntax in tap!
```
since the **secman.rb file is empty**.

**Comment by abdfnx** [comment]
hi @arcesino, until now we didn't release the new version of secman, we we release it, you can install it, ok

**Comment by abdfnx** [comment]
@arcesino hi again, can you try to install `secman` right now ?

**Comment by arcesino** [comment]
@abdfnx I can confirm I was able to install it using command below, as stated in https://secman.dev/download:
```
brew install scmn-dev/tap/secman
```

Thanks so much for your suppport!

**Comment by abdfnx** [comment]
> @abdfnx I can confirm I was able to install it using command below, as stated in https://secman.dev/download:
> ```
> brew install scmn-dev/tap/secman
> ```
> 
> Thanks so much for your suppport!

Glad to help
