### ISSUE TITLE
Create Our Own `API` Website

### ISSUE THREAD

**Issue by abdfnx** [scmn-dev/secman#66]
I think we should create our own `API` website.

for `secman-desktop` & `secman signup` website

> what do you think @iMRxM7mD @Timothee-Cardoso @david-tomson

**Comment by Timothee-Cardoso** [comment]
yes, I think it's a good idea

**Comment by Timothee-Cardoso** [comment]
and which platform we'll use ?

**Comment by abdfnx** [comment]
> and which platform we'll use ?

what about **Heroku**

and the database well build by `PostgreSQL`

**Comment by Timothee-Cardoso** [comment]
Heroku is powerfull, it's done.

**Comment by abdfnx** [comment]
it's done, secman api server is deploying now at [**api.secman.dev**](https://api.secman.dev)

**Comment by david-tomson** [comment]
good job boys
